const htmlPlugin = require("html-webpack-plugin");
const isDev = process.env.NODE_ENV === "development";

module.exports = {
  mode: isDev ? "development" : "production", // by default it's production mode, in production it's minify the code
  entry: "./src/index.js",
  //   devtool: "eval-source-map", // by default it's using the eval
  module: {
    rules: [
      /**
      {
        test: /\.css$/, // every file which ends with .css
        use: ["style-loader", "css-loader"], // right to left conversion
        /**
         * 1. css-loader will run and takes the css file and turns into the js file -> this is the work of css loader
         * 2. style-loader take that js code and inject that code into the dom.
         * We've seen sometimes style tag present there but we don't define them this is generated by style-loader
         
      },
      */
      {
        test: /\.scss$/, // every file which ends with .scss
        use: [
          "style-loader", // 3. take that .js and inject into the dom
          "css-loader", // 2. convert .css to js
          "sass-loader", // 1. compile scss to css
        ],
      },
    ],
  },
  plugins: [
    new htmlPlugin({
      template: "./index.html",
      title: isDev ? "anuj panwar" : "Anuj Panwar",
      heading: isDev ? "Welcome!" : "Welcome guys!",
    }),
  ],
};
